Universe = vanilla

Output = /usatlas/u/qlei/batch_output_files/eventloop_arrays/eventloop_arrays.$(Cluster).$(Process).out
Error = /usatlas/u/qlei/batch_output_files/eventloop_arrays/eventloop_arrays.$(Cluster).$(Process).err
Log = /usatlas/u/qlei/batch_output_files/eventloop_arrays/eventloop_arrays.$(Cluster).$(Process).log

Executable = /usatlas/u/qlei/dev/af-benchmarking/NTuple_Hist/event_loop/BNL/columnar/run_eventloop_arrays.sh

request_memory = 3GB
request_cpus = 1

Queue 1
