name: "Parse Benchmark Logs"
description: "Parse benchmark logs and generate JSON payload"
inputs:
  job:
    description: "Job name (e.g., rucio, eventloop-columnar, evnt-native)"
    required: true
  log-file:
    description: "Path to log file"
    required: true
  log-type:
    description:
      "Type of log parser to use (e.g., rucio, athena, coffea, eventloop,
      fastframes)"
    required: true
  cluster:
    description: "Cluster name (e.g., UC-AF, SLAC-AF, BNL-AF)"
    required: true
  kibana-token:
    description: "Token for benchmark identification"
    required: true
  kibana-kind:
    description: "Kind for benchmark identification"
    required: true
  host:
    description: "Hostname to identify the machine running the job"
    required: true
  payload-file:
    description: "Path to payload file for size calculation (optional)"
    required: false
    default: ""
  output-file:
    description: "Output JSON file path"
    required: false
    default: "payload.json"

outputs:
  payload-file:
    description: "Path to the generated payload JSON file"
    value: ${{ inputs.output-file }}

runs:
  using: "composite"
  steps:
    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.9.3
      with:
        pixi-version: v0.49.0
        environments: kibana

    - name: Parse log file
      shell: bash
      run: |
        pixi run -e kibana python parsing/scripts/ci_parse.py \
          --job "${{ inputs.job }}" \
          --log-file "${{ inputs.log-file }}" \
          --log-type "${{ inputs.log-type }}" \
          --cluster "${{ inputs.cluster }}" \
          --token "${{ inputs.kibana-token }}" \
          --kind "${{ inputs.kibana-kind }}" \
          --host "${{ inputs.host }}" \
          --payload-file "${{ inputs.payload-file }}" \
          --output "${{ inputs.output-file }}"
