Universe = vanilla

Output = /home/selbor/ntuple/eventloop_arrays/eventloop_arrays.$(Cluster).$(Process).out
Error = /home/selbor/ntuple/eventloop_arrays/eventloop_arrays.$(Cluster).$(Process).err
Log = /home/selbor/ntuple/eventloop_arrays/eventloop_arrays.$(Cluster).$(Process).log

Executable = /home/selbor/AF-Benchmarking/NTuple_Hist/event_loop/UC/run_eventloop_arrays.sh

request_memory = 3GB
request_cpus = 1

Queue 1
