Universe = vanilla

Output = /home/selbor/ntuple/eventloop_noarrays/eventloop_noarrays.$(Cluster).$(Process).out
Error = /home/selbor/ntuple/eventloop_noarrays/eventloop_noarrays.$(Cluster).$(Process).err
Log = /home/selbor/ntuple/eventloop_noarrays/eventloop_noarrays.$(Cluster).$(Process).log

Executable = /home/selbor/AF-Benchmarking/NTuple_Hist/event_loop/UC/run_eventloop_noarrays.sh

request_memory = 3GB
request_cpus = 1

Queue 1
