general:
  debug_level: DEBUG
  
  # Paths
  input_filelist_path: "/srv/input/ana_filelist.txt"
  input_sumweights_path: "/srv/input/sum_weights.txt"
  output_path_histograms: "/srv/output/"


  # Weights
  default_sumweights: "NOSYS"
  default_event_weights: "weight_mc_NOSYS * weight_pileup_NOSYS"
  
  default_reco_tree_name: "analysis"

  # path to the file with cross-sections
  xsection_files: ["/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/dev/PMGTools/PMGxsecDB_mc16.txt"]

  # name of the custom class
  custom_frame_name: "TutorialClass"


  # automatic systematics?
  automatic_systematics: True
  nominal_only: False

  # Which objects to create lorentz vectors for
  create_tlorentz_vectors_for: ["ph"]

  number_of_cpus: 1

  luminosity:
      mc20e: 59700

# Define regions
regions:
  - name: "Muon"
    selection: "true" 
    variables:
      - name: "ph_pt"
        title: "p_{T}; p_{T} [GeV];Events"
        definition: "ph1_pt1_NOSYS"
        type: "double"
        binning:
          min: 0
          max: 1000
          number_of_bins: 100


#regions:
#  - name: "met"
#    selection: "met_met_NOSYS>0"
#    variables:
#      - name: "met_met"
#        title: "met; met [GeV];Events"
#        definition: "met_met_NOSYS"
#        type: "float"
#        binning:
#          min: 0
#          max: 1000
#          number_of_bins: 10

# define samples
samples:
  - name: "example_FS"
    dsids: [700402]
    campaigns: ["mc20e"]
    simulation_type: "fullsim"
