Universe = vanilla


Output = /usatlas/u/jroblesgo/batch_output_files/evnt/native/myjob.$(Cluster).$(Process).out
Error = /usatlas/u/jroblesgo/batch_output_files/evnt/native/myjob.$(Cluster).$(Process).err
Log = /usatlas/u/jroblesgo/batch_output_files/evnt/native/myjob.$(Cluster).$(Process).log

Executable = /usatlas/u/jroblesgo/AF-Benchmarking/EVNT/BNL/run_evnt_native_batch.sh

request_memory = 3GB
request_cpus = 1

Queue 1
