Universe = vanilla

Output = /usatlas/u/jroblesgo/batch_output_files/eventloop/arrays_myjob.$(Cluster).$(Process).out
Error = /usatlas/u/jroblesgo/batch_output_files/eventloop/arrays_myjob.$(Cluster).$(Process).err
Log = /usatlas/u/jroblesgo/batch_output_files/eventloop/arrays_myjob.$(Cluster).$(Process).log

Executable = /home/selbor/AF-Benchmarking/NTuple_Hist/event_loop/UC/run_eventloop_arrays.sh

request_memory = 3GB
request_cpus = 1

Queue 1
