name: "Setup Globus"
description:
  "Set up the ~/.globus directory with necessary files and permissions for using
  Grid computing and VOMS (Virtual Organization Membership Service)."
inputs:
  voms-usercert:
    description: "Public key and user information (usercert.pem)"
    required: true
    default: ${{ secrets.VOMS_USERCERT }}
  voms-userkey:
    description: "Private key (userkey.pem)"
    required: true
    default: ${{ secrets.VOMS_USERKEY }}
runs:
  using: "composite"
  steps:
    - name: Mask Inputs
      run: |
        echo ::add-mask::${{ inputs.VOMS_USERCERT }}
        echo ::add-mask::${{ inputs.VOMS_USERKEY }}
      shell: bash

    - name: Create directory
      run: mkdir -p ~/.globus
      shell: bash

    - name: Create files
      run: |
        cat > ~/.globus/usercert.pem << 'EOF'
        ${{ inputs.VOMS_USERCERT }}
        EOF
        cat > ~/.globus/userkey.pem << 'EOF'
        ${{ inputs.VOMS_USERKEY }}
        EOF
      shell: bash

    - name: Set permissions
      run: |
        chmod 644 ~/.globus/usercert.pem
        chmod 600 ~/.globus/userkey.pem
      shell: bash
