name: "Parse and Upload to Kibana"
description: "Parse benchmark logs and upload results to Elasticsearch/Kibana"
inputs:
  job-type:
    description: "Type of job (rucio, evnt-native, etc.)"
    required: true
  log-file:
    description: "Path to log file"
    required: true
  cluster:
    description: "Cluster name (e.g., UC-AF, SLAC-AF, BNL-AF)"
    required: true
  es-username:
    description: "Elasticsearch username"
    required: true
  es-password:
    description: "Elasticsearch password"
    required: true
  kibana-token:
    description: "Token for benchmark identification"
    required: true
  kibana-kind:
    description: "Kind for benchmark identification"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.9.3
      with:
        pixi-version: v0.49.0
        environments: kibana

    - name: Parse and upload
      shell: bash
      run: |
        # Juan will provide the parsing script implementation
        # Expected interface (to be confirmed):
        pixi run -e kibana python parsing/scripts/ci_parse_and_send.py \
          --job-type "${{ inputs.job-type }}" \
          --log-file "${{ inputs.log-file }}" \
          --cluster "${{ inputs.cluster }}" \
          --es-username "${{ inputs.es-username }}" \
          --es-password "${{ inputs.es-password }}" \
          --token "${{ inputs.kibana-token }}" \
          --kind "${{ inputs.kibana-kind }}"
