general:
  debug_level: DEBUG
  
  # Paths
  input_filelist_path: "/home/selbor/input/ana_filelist.txt"
  input_sumweights_path: "/home/selbor/input/sum_weights.txt"
  output_path_histograms: "/home/selbor/output/"


  # Weights
  default_sumweights: "NOSYS"
  default_event_weights: "weight_beamspot"
  
  default_reco_tree_name: "analysis"

  # path to the file with cross-sections
  xsection_files: ["/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/dev/PMGTools/PMGxsecDB_mc16.txt"]

  # name of the custom class
  custom_frame_name: "TutorialClass"


  # automatic systematics?
  automatic_systematics: True
  nominal_only: False

  # Which objects to create lorentz vectors for
  create_tlorentz_vectors_for: ["ph"]

  number_of_cpus: 4

  luminosity:
    mc23a: 26071.4

# Define regions
regions:
  - name: "Muon"
    selection: "true" 
    variables:
      - name: "ph_pt"
        title: "Leading jet p_{T}; Leading jet p_{T} [GeV];Events"
        definition: "ph1_pt1_NOSYS"
        type: "double"
        binning:
          min: 0
          max: 1000
          number_of_bins: 10
#regions:
#  - name: "met"
#    selection: "met_met_NOSYS>0"
#    variables:
#      - name: "met_met"
#        title: "met; met [GeV];Events"
#        definition: "met_met_NOSYS"
#        type: "float"
#        binning:
#          min: 0
#          max: 1000
#          number_of_bins: 10

# define samples
samples:
  - name: "example_FS"
    dsids: [700402]
    campaigns: ["mc20a"]
    simulation_type: "fullsim"
