Universe = vanilla


Output = /usatlas/u/qlei/batch_output_files/truth3/el/myjob.$(Cluster).$(Process).out
Error = /usatlas/u/qlei/batch_output_files/truth3/el/myjob.$(Cluster).$(Process).err
Log = /usatlas/u/qlei/batch_output_files/truth3/el/myjob.$(Cluster).$(Process).log

Executable = /usatlas/u/qlei/AF-Benchmarking/TRUTH3/BNL/EL9/run_truth3_el9_batch.sh

request_memory = 3GB
request_cpus = 1

Queue 1
