Universe = vanilla


Output = /usatlas/u/jroblesgo/batch_output_files/evnt/el/myjob.$(Cluster).$(Process).out
Error = /usatlas/u/jroblesgo/batch_output_files/evnt/el/myjob.$(Cluster).$(Process).err
Log = /usatlas/u/jroblesgo/batch_output_files/evnt/el/myjob.$(Cluster).$(Process).log

Executable = /usatlas/u/jroblesgo/AF-Benchmarking/EVNT/BNL/run_evnt_el9_batch.sh

request_memory = 3GB
request_cpus = 1

Queue 1
