Universe = vanilla


Output = /usatlas/u/jroblesgo/batch_output_files/evnt/centos/myjob.$(Cluster).$(Process).out
Error = /usatlas/u/jroblesgo/batch_output_files/evnt/centos/myjob.$(Cluster).$(Process).err
Log = /usatlas/u/jroblesgo/batch_output_files/evnt/centos/myjob.$(Cluster).$(Process).log

Executable = /usatlas/u/jroblesgo/AF-Benchmarking/EVNT/BNL/CentOS7/run_evnt_centos7_batch.sh

request_memory = 3GB
request_cpus = 1

Queue 1
